### PR TITLE
Finalesque Dev push

### PR DESCRIPTION
**Pull request by parsnbl**

### CODE REVIEW

**Review by philzmintmojito — APPROVED** [review]
Amazing!

**Review by haroldreeves — COMMENTED** [review]
Amazing!!!!

**Review by adrianinsingo — APPROVED** [review]
WOOOO!

**Review by connallyjae — APPROVED** [review]
Looks amazing! Ya'll did an awesome job! Best team ever!!

**Review by haroldreeves — APPROVED** [review]

**Pull request merged**
